<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="frmMain.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>frmMain.resx</DependentUpon>
    </Compile>
    <Compile Update="Menu.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Menu.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="frmMain.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>frmMain.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Menu.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Menu.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>